name: figma_font_gen_cli
description: Figma Font Generator it's CLI tool for generating font from Figma url image sets
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
